### ISSUE TITLE
The best SCRCPY GUI going (BUT!)

### ISSUE THREAD

**Issue by JASHIKO** [Frontesque/scrcpy-plus#1]
Just wanted to say that this is the best and most reliable SCRCPY GUI available. All the other ones are a nightmare to use or just don't have English language support. The only downside to this so far is the lack of options. It would be nice to see more of the commands listed. If you do end up adding them at some stage I add them to my review (linked below) and probably make a YouTube video about it. We are quite a big source for SCRCPY troubleshooting and set up content. 
www.downloadsource.net ](https://www.downloadsource.net/how-to-get-scrcpy-gui-graphic-user-interface/n/21549/)

Cheers!

**Comment by Frontesque** [comment]
hey, thanks for taking your time to drop a suggestion. I'll definitely look into adding more scrcpy options and bumping the scrcpy base. I kind of forgot about this project honestly but it won't take much time to update that stuff. maybe 5-10 minutes.

**Comment by JASHIKO** [comment]
Not a problem! I've been using SCRCPY for ages and just saw your post on the Reddit sub. I tested all of the known SCRCPY GUI tools today while writing an article for our website. Yours was by far the easiest to use with the best interface, it was just lacking a few more options. 

I know you just whacked it together in your spare time but you did a great job, seems like it would be a shame to let it go to waste. If you do end up adding some extra stuff, I'll hold off making a YouTube about it for a while longer. SCRCPY is quite a popular part of our channel so this would be a great little addition :) 

Cheers again! The link should be working now. I was in the middle of putting it together when I posted. I wasn't expecting such a fast reply!

**Comment by Frontesque** [comment]
thanks for the feedback. I'll definitely improve on it later today  this was created so that my friends can easily screenshare their android devices through discord and Skype on their computer so that I can help them with tech issues and without teaching them the command line.

**Comment by JASHIKO** [comment]
This is the kind of thing I should be using for my parents! But I'd have to teach them discord first ahahaha.

**Comment by Frontesque** [comment]
Hey there, I've updated the app quite a bit since you've taken a look at it. Are there still any suggestions that you have feature-wise? I hope I have gotten most of what you wanted so far 😀

**Comment by JASHIKO** [comment]
> Hey there, I've updated the app quite a bit since you've taken a look at it. Are there still any suggestions that you have feature-wise? I hope I have gotten most of what you wanted so far 😀

Awesome! I'll check it out ASAP! It was already great so whatever you've added will only make it better! I'll try to get a video up about it at some stage as well.

**Comment by Frontesque** [comment]
I've also been working on some stuff that should take this app far beyond just the realms of SCRCPY. 😉
<img src="https://api.celeste.photos/uploads/ee556ec1-7ac3-44ea-a1f0-541667d58879/h6vMrI0B.gif" />

**Comment by JASHIKO** [comment]
So much potential! I'm looking forward to seeing where it goes. Have you seen an increase in traffic lately at all?

**Comment by Frontesque** [comment]
> So much potential! I'm looking forward to seeing where it goes. Have you seen an increase in traffic lately at all?

When you posted the article, the download count spiked a bit. That's all that I'm tracking, and it's public information that you can view at https://api.github.com/repos/Frontesque/scrcpy-plus/releases
