### ISSUE TITLE
[MacOS] Device not detected

### ISSUE THREAD

**Issue by Thelm76** [Frontesque/scrcpy-plus#10]
WHEN I launch scrcpy+
AND I try to connect to my android device
THEN The device doesn't appear in the list and there are no devices found

![image](https://user-images.githubusercontent.com/25480150/197558995-f26ffd90-e070-477f-a3d4-ecf2bd1e9568.png)

![image](https://user-images.githubusercontent.com/25480150/197559447-c62e8dbd-e972-4026-8b8a-6f7d14a19391.png)

![image](https://user-images.githubusercontent.com/25480150/197559602-59335abf-827b-478f-adb8-55e0082f69b8.png)

**Comment by Thelm76** [comment]
I'll investigate this issue and send logs when I get time

**Comment by Frontesque** [comment]
> I'll investigate this issue and send logs when I get time

alright. sounds good.

**Comment by Frontesque** [comment]
could you open up the Remote Debugging Console in SCRCPY+ and run `$nuxt.$adb("devices")` and send me the output?

**Comment by Thelm76** [comment]
I'm not familiar enough with JS debugging, could you explain to me how to open this remote console please (I'm using VSCode)?

**Comment by Frontesque** [comment]
> I'm not familiar enough with JS debugging, could you explain to me how to open this remote console please (I'm using VSCode)?

sure!

follow the building guide to install your dependencies (I assume you've already done this) and instead of running `yarn build` run `yarn dev` and it should pop-up automatically!

**Comment by Thelm76** [comment]
> > I'm not familiar enough with JS debugging, could you explain to me how to open this remote console please (I'm using VSCode)?
> 
> sure!
> 
> follow the building guide to install your dependencies (I assume you've already done this) and instead of running `yarn build` run `yarn dev` and it should pop-up automatically!

Well okay I already got the console then

**Comment by Thelm76** [comment]
I managed to get some info using logs : 
![image](https://user-images.githubusercontent.com/25480150/199729705-68df9cb6-8167-4c1f-9a77-4330c3032b2f.png)

**Comment by Thelm76** [comment]
Okay I found it the bug it's working now :D

**Comment by Frontesque** [comment]
> Okay I found the bug it's working now :D
I do suggest compiling an older version of SCRCPY+ (v1.5.x) for now as v2 is still quite buggy. When V2 comes out, you can use that but you can just modify 1.5.x with these changes as a temporary fix.

Here is the [v1.5.2 codebase](https://github.com/Frontesque/scrcpy-plus/tree/1.5.2).
