### ISSUE TITLE
Report to Microsoft the app is safe

### ISSUE THREAD

**Issue by falcon-Z** [Frontesque/scrcpy-plus#17]
When downloading the app from Microsoft Edge browser the Download gets blocked by Microsoft defender as the app and flags it as potentially unsafe as the app doesn't get downloaded often.
Therefore, you have to report the app as safe to Microsoft. Here's how

1. Download an exe version of the app from within Microsoft Edge
2. When the download gets blocked Click ... and choose keep
3. When the following warning shows up select **Show More** then **Report this app as Safe** 
![image](https://user-images.githubusercontent.com/28111283/208838302-4f882928-43c1-4530-8a37-119867d63dcb.png)

You will be redirected to Microsoft's feedback page.

**Comment by Frontesque** [comment]
This is an open source project. Almost all open source projects are marked as uncommonly downloaded. Both Chrome and Edge do this and there is no work around unless the project just becomes more popular.
