### ISSUE TITLE
Wireless debugging issue and scrcpy plus

### ISSUE THREAD

**Issue by chiragnahata** [Frontesque/scrcpy-plus#19]
My wireless debugging turns off after my phone has locked. I am using scrcpy+. So i need to always connect to my device by mannually pairing it and keeping the phone on. If my screen turns off and locks the wireless debugging turns off. So is there a way to not turn the wireless debugging off and connect otscrcpy+ without pairing it everytime.

https://www.reddit.com/r/androiddev/comments/1013ld8/wireless_debugging_issue/

**Comment by Frontesque** [comment]
As someone commented in the reddit post,

```
I think this is manufacturer specific and related to battery management killing off the connection. My OnePlus 6T disconnects after the screen locks. My pixel 5 stays connected forever until I change wifi or manually disconnect.

Hopefully there is a system app somewhere that just needs its battery setting set to unrestricted?
```

I don't believe that this is a SCRCPY+ issue.
