### ISSUE TITLE
Wrong Build number

### ISSUE THREAD

**Issue by NZ-Wanderer** [Frontesque/scrcpy-plus#25]
Hi there,
My device (Huawei P30 Pro) has build 12.0.0.134, however, scrpy-plus is telling me I only have android 10 hence I cannot connect audio or wifi., any workarounds or fixes please?

**Comment by Frontesque** [comment]
> however, scrpy-plus is telling me I only have android 10

as you can see in [device.vue](https://github.com/Frontesque/scrcpy-plus/blob/c03145ddd6630e2209d476690ffcc3ead746e88e/src/renderer/components/device.vue#L59-L64), we ping the device itself for its build number. It's possible that your phone is returning the wrong build number. Is it possible that Huawei uses a different [prop](https://emteria.com/learn/android-system-properties) for the build ID?

```js
[...]
{
  title: "System Build Number",
  icon: "mdi-wrench",
  command: "adb shell getprop ro.build.id", // This is the line that pings the device for the build id
  data: null,
},
[...]
```

**Comment by NZ-Wanderer** [comment]
Possibly, I managed to find this, and it looks like ro.build.id does not show the actual build number.. (Please note I know nothing about this sort of thing..) :)
![2023-04-07 11_31_22-huawei_quirks_getprop at master · berkeley-dev_huawei_quirks - Brave](https://user-images.githubusercontent.com/447796/230512080-cc1de9ca-8e64-4505-864d-14e65ef36bf9.jpg)

**Comment by Frontesque** [comment]
> Possibly, I managed to find this, and it looks like ro.build.id does not show the actual build number..  [...]

this is exactly what im checking. Can you find anything in there that shows the actual build numbers? This is a mess up on Huawei's part, not mine though haha

**Comment by Frontesque** [comment]
> ro.build.description ro.build.display.id ro.build.version.emui ro.build.version.release
> 
> These all show 8.0.0 which is the build number, the last one would be my guess as it shows just the main version number.

On a standard device, each of those give the following responses.

```bash
# assuming android 10
ro.build.description=sdk_phone_armv7-userdebug 10 QPP6.190730.006 5803371 test-keys
ro.build.display.id=sdk_phone_armv7-userdebug 10 QPP6.190730.006 5803371 test-keys
ro.system.build.version.release=10

# 'ro.build.version.emui' doesn't exist on stock android
```

This seems to be an issue with your manufacturer. They must have gotten the build data from [the android build props example page](https://android.googlesource.com/platform/prebuilts/fullsdk/platforms/android-29/+/50e91e4827cdd58e191c942d33db0cc61362cdf6/build.prop) and forgot to change it. I can't really help you here.
