### ISSUE TITLE
Winget Support 

### ISSUE THREAD

**Issue by milindgoel15** [Frontesque/scrcpy-plus#26]
I just saw a new update available when I opened scrcpy-plus but since I prefer to update via Winget, I checked and there was no update there. I want to know how much time does it generally take for Winget to process new updates and distribute them?

**Comment by Frontesque** [comment]
I have no clue. I didn't realize you could download GitHub repos from Winget?

**Comment by milindgoel15** [comment]
Then it was someone else who published the winget repo?

**Comment by Frontesque** [comment]
yep, must be. use that at your own risk. I have nothing to do with it.

**Comment by milindgoel15** [comment]
Could you do it? Publish as a developer

**Comment by Frontesque** [comment]
> Could you do it? Publish as a developer

sure I'll look into it but it may be a week or two as I'm leaving for vacation today. I pushed out the v2.0 update last minute because it felt overdue. in the meantime, you can use the portable version if you're worried about leaving leftover data on your machine.

**Comment by milindgoel15** [comment]
No problems 👍👍

**Comment by ShayBox** [comment]
Could someone update the winget package from 1.5 to 2.0?

**Comment by milindgoel15** [comment]
I could do it but it would be better to have developer do it himself, anytime he releases a new update.

**Comment by milindgoel15** [comment]
created a pr to submit a 2.0.0 update to winget repo. Once the pr is merged, you will be able to download 2.0.0 via winget
https://github.com/microsoft/winget-pkgs/pull/106899

**Comment by milindgoel15** [comment]
Also, updated the readme to include method for winget installation.
https://github.com/Frontesque/scrcpy-plus/pull/33

**Comment by Frontesque** [comment]
> I could do it but it would be better to have developer do it himself, anytime he releases a new update.

I have to say, I'm not very interested in having to submit a PR to the winget repo every time I update this repository. I feel like its pretty redundant. It also doesn't seem like a lot of people use winget.

**Comment by Frontesque** [comment]
I'm not familiar with updating AUR packages or Flatpak repos. I use RHEL for linux, so everyone just has their own COPRs

**Comment by milindgoel15** [comment]
The PR is merged for version 2.0.0. closing this issue now
