### ISSUE TITLE
Remember devices that connected through wireless adb

### ISSUE THREAD

**Issue by Jnss98b** [Frontesque/scrcpy-plus#3]
I usually use wireless adb bc I don't feel like grabbing the usb cable and every time I have to input the IP address and port number. It would be a great quality of life improvement for scrcpy+ to remember past devices and/or let you save devices and rename them

**Comment by Frontesque** [comment]
Looking back on this; I don't think that this is possible due to how android's wireless tethering works. If you already set up the device, you can just click "skip" on the first step.

**Comment by Jnss98b** [comment]
I recently came across this plugin for android studio/intellij that remembers wireless adb devices as long as you plug them in once for setup so maybe you could look into this and implement it for scrcpy+? @Frontesque 

https://github.com/y-polek/ADB-Wi-Fi
