### ISSUE TITLE
Windows - After closing remains in task manager

### ISSUE THREAD

**Issue by psyhlo** [Frontesque/scrcpy-plus#30]
When the app is close, doesn't close all processes 
![image](https://user-images.githubusercontent.com/1803170/234794169-a4c6a12a-cc55-4ac3-b28d-8709c5190fc3.png)

**Comment by bigfoxtail** [comment]
mee too

**Comment by Frontesque** [comment]
are you both using the latest version of scrcpy-plus? (2.0.0)

**Comment by psyhlo** [comment]
![image](https://github.com/Frontesque/scrcpy-plus/assets/1803170/1abf76f0-7a14-468d-b848-b128c507f70d)

**Comment by Frontesque** [comment]
I believe that this is because ADB is continuing to run in the background. I honestly need to rewrite this program.

**Comment by Frontesque** [comment]
this should be fixed as of 2.1.1 I'll reopen it if you deem that it is not fixed.
