### ISSUE TITLE
Android Phone Video Recording Does Not Work

### ISSUE THREAD

**Issue by MyNameIsRocky** [Frontesque/scrcpy-plus#31]
Hello, the video recording on the android phone while running scrcpy plus does not work. It says failure to record. Also says video codec being used by another application. I have checked and restarted the PC to ensure no other "video" app is being used, it still does not work. Thank you Rocky

**Comment by Frontesque** [comment]
I believe this is an issue with SCRCPY, not my program. There is nothing that I can do about this until they fix it.
