### ISSUE TITLE
Help with Spanish translation

### ISSUE THREAD

**Issue by CrazyBytesVE** [Frontesque/scrcpy-plus#32]
Hi, Your module is great. 

I would love to help you to translate the app to spanish. 

I would also love you to upload your app to Winget to make it easier to update via WingetUI and that will help you to spread the word about your app.

**Comment by milindgoel15** [comment]
> I would also love you to upload your app to Winget to make it easier to update via WingetUI and that will help you to spread the word about your app.

It is already available via winget. Use this command:
`winget install Front.scrcpy+`

**Comment by Frontesque** [comment]
> I would love to help you to translate the app to spanish.

Currently, there are no translation files. I'm working on rewriting the app. I'll add language compatibility to the new version.

**Comment by Frontesque** [comment]
language files will be available in v3 
![image](https://github.com/user-attachments/assets/a33239f3-95b9-46b3-bf50-2198c3a27b43)
