### ISSUE TITLE
Display screen shared will crash all of sudden while inactive.

### ISSUE THREAD

**Issue by milindgoel15** [Frontesque/scrcpy-plus#34]
I am not really sure it crashes while it's inactive but the screen sharing crashes and Scrcpy+ still shows it's running. Then I need to restart the app or tap on the changelog button and go back to refresh the main page to make the UI update.

Is there a way to get logs of this?

**Comment by Frontesque** [comment]
> Is there a way to get logs of this?

all logs should be in the developer console (ctrl + shift + i)

**Comment by milindgoel15** [comment]
Although, since I created this issue, it never crashed out of a sudden. lol
For some reason, I got a crash when I was closing android studio. It killed the whole daemon process

```logs
Uncaught (in promise) TypeError: t.startsWith is not a function
    at 4fbe28d.js:1:89135
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
node:internal/process/task_queues:96 Uncaught (in promise) * daemon not running; starting now at tcp:5037
* daemon started successfully
```

**Comment by Frontesque** [comment]
This usually means that the ADB server is stopping. It's likely the device end because SCRCPY+ polls ADB every few seconds.
