### ISSUE TITLE
Sensitive Content unavailable in Android 11 and above

### ISSUE THREAD

**Issue by IkelAtomig** [Frontesque/scrcpy-plus#36]
In my device running Android 9.0 (Pie). I could sensitive Content such as WhatsApp View Once message when using SCRCPY+. But now I can't because it loads a black screen in my new Phone.

My Device is Android 13.

**Comment by Frontesque** [comment]
This is an issue with android. Since  this project is built on top of SCRCPY, you should submit the bug report to them instead of me.
