### ISSUE TITLE
It does not have a full screen feature

### ISSUE THREAD

**Issue by Ab2lrahim99** [Frontesque/scrcpy-plus#37]
Please fix the full screen mode, when I put it in full screen mode, unfortunately the top and bottom bars are visible.

**Comment by Frontesque** [comment]
Please provide more information

**Comment by Frontesque** [comment]
closed due to inactivity

**Comment by xrishox** [comment]
i would also like to have a full screen mode. what i mean by this is like when a video player or a game goes full screen it gets rid of the title bar for the app and the taskbar with the start menu and stuff.
