### ISSUE TITLE
Any Linux Update Please? | The app keeps showing popups about updates

### ISSUE THREAD

**Issue by AlexNeOon** [Frontesque/scrcpy-plus#39]

**Comment by AlexNeOon** [comment]
![image](https://github.com/Frontesque/scrcpy-plus/assets/138698529/b0a21e2b-f9e4-405e-8d70-1f00a9cda7d5)

**Comment by Frontesque** [comment]
You are able to build it yourself if you have nodejs v16 installed by following [BUILD.md](https://github.com/Frontesque/scrcpy-plus/blob/main/BUILDING.md)
