### ISSUE TITLE
Share stops randomly

### ISSUE THREAD

**Issue by Void2258** [Frontesque/scrcpy-plus#40]
The share is closing at random intervals, for no clear reason. It will just stop and the window closes. No error message or other indication of issue. The UI does not close, but the "start" button will no longer be there, and the UI must be closed and restarted to get the button back and be able to resume the share. 

The connection details are not lost during this (you do not have to reenter the wireless codes, ips, etc.) and once you do restart the ui, it will immediately be able to resume.

**Comment by Frontesque** [comment]
interesting. what device are you connected to?

**Comment by Void2258** [comment]
galaxy tab s7 to windows 10 pc.

**Comment by Frontesque** [comment]
I'm not certain. I'm not sure why it would be disconnecting as there is never a disconnect being done while the application is running. I don't have this happening with any of my samsung devices (Samsung S4, S6, S6 Edge). I don't have a Galaxy Tab to test this.

**Comment by Frontesque** [comment]
should be fixed in [f8b6cfd](https://github.com/Frontesque/scrcpy-plus/commit/f8b6cfd847cba6776aad71257b4d8820d03ab629)
