### ISSUE TITLE
Tauri version?

### ISSUE THREAD

**Issue by rp1231** [Frontesque/scrcpy-plus#43]
Have you considered making this with tauri?
That would bring down the size of the program to a few mb's.
https://tauri.app/

**Comment by Frontesque** [comment]
Last I heard of Tauri, it was in a pre-release state. I'm not familiar with how to use it, but I am in the process of rewriting the app. I'm not sure if that would make sense to use though, as I doubt external dependencies can be bundled with the app.

**Comment by Frontesque** [comment]
I'll look into using it for the rewrite.
