### ISSUE TITLE
build new app for win 11 arch 64

### ISSUE THREAD

**Issue by MohamedSonata** [Frontesque/scrcpy-plus#46]
im trying to build new one from source code and the build complete done but when open the app it's return this error . and i already install it and the same error : 
Error Starting SCRCPY+
This error could be caused by SCRCPY not being properly installed on your OS.
More Details
Error: Command failed: cd resources/scrcpy/&scrcpy --version
This version of C:\Users\mson\Downloads\Compressed\scrcpy-plus-2.0.2\scrcpy-plus-2.0.2\build\win-unpacked\resources\scrcpy\scrcpy.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by Frontesque** [comment]
you need to load your own version of SCRCPY into the `resources/scrcpy` folder on windows.

**Comment by MohamedSonata** [comment]
bro did u can help us and add these Features to advanced Section  Args {--window-width , --window-height , --window-x , --window-y } and allow the user to put his custom points  .. this will allow the view window to set in the posstion and sizes as default not need to resize it every time Please

**Comment by Frontesque** [comment]
> bro did u can help us and add these Features to advanced Section  Args {--window-width , --window-height , --window-x , --window-y } and allow the user to put his custom points  .. this will allow the view window to set in the posstion and sizes as default not need to resize it every time Please 
> 
> 

this is not part of the original issue.

it takes more time to input the numbers than to click and drag. if you're looking for automation, make a script.
