### ISSUE TITLE
Nothing happens when you click "Start Scrcpy"

### ISSUE THREAD

**Issue by EldrinSMP** [Frontesque/scrcpy-plus#48]
Scrcpy+ v.2.0.2 on Windows 11 Pro connecting to a Samsung Galaxy S22 Ultra on Android 14.

After connecting my device via ADB and setting up the desired options (Keep awake), I click on "Start ScrCpy" and it displays "SCRCPY is currently running" but nothing else happens. There is no screen mirror window that pops up or any other indication that it activated. In fact, I can''t end the Scrcpy session without closing out of the program entirely. This happens whether the connection is wired or wireless.

**Comment by Frontesque** [comment]
Base SCRCPY was just bumped to 2.3.1. Please let me know if this resolves your issue.

**Comment by EldrinSMP** [comment]
@Frontesque  I am no longer running Windows, so I sadly can't answer that. I CAN say it works great on Solus!

**Comment by Frontesque** [comment]
It's the same codebase across platforms, so I'll consider this resolved.
