### ISSUE TITLE
scrcpy update

### ISSUE THREAD

**Issue by LuminarySage** [Frontesque/scrcpy-plus#58]
Seems like the current scrcpy version is outdated with the latest android update as when I start screen mirroring, it says it started but nothing showed up. I tried to use the latest cli scrcpy version (2.6 as of this writing) and it worked fine.

 - **OS:** Windows 11 23H2
 - **scrcpy-plus version:** 2.1.0
 - **Device model:** Google Pixel Fold
 - **Android version:** 14 (June update)

**Comment by Frontesque** [comment]
As mentioned in the readme, the build chain for this app is kind of outdated. I just found a reliable way to get it working again, so I'm working on an update currently.
