### ISSUE TITLE
[Feature] Provide Mac version

### ISSUE THREAD

**Issue by timelic** [Frontesque/scrcpy-plus#62]
Because it was developed with electron, it should be easy to build the Mac version, but it seems that only Windows is supported now.

**Comment by Frontesque** [comment]
To build the Mac version, you need a Mac.

I don't have one because they're out of my price range.

Instructions to build the MacOS version can be found in the build guide

https://github.com/Frontesque/scrcpy-plus/blob/main/BUILDING.md
