### ISSUE TITLE
Download Link (WINDOWS) Broken :(

### ISSUE THREAD

**Issue by JASHIKO** [Frontesque/scrcpy-plus#7]
Hey mate :) 
I hope you're well. 
Just a heads up your Windows download links are no longer working. 
I've had a few people on YouTube ask about it. 
Let me know when you get it up and running again and I'll forward the message to them. 

Cheers!

**Comment by Frontesque** [comment]
fixed in https://github.com/Frontesque/scrcpy-plus/commit/91f04301bc3143ad917f1dc7a8bb42d3d635e0da
